/*

 LEER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __leer_h_INCLUDE
#define __leer_h_INCLUDE

#define leerWidth 18
#define leerHeight 4
#define leerBank 0

extern const unsigned char leer[];

#endif

/* End of LEER.H */
