/*

 SHIELD-2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\github\vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __shield_2_h_INCLUDE
#define __shield_2_h_INCLUDE

#define schild2Width 18
#define schild2Height 4
#define schild2Bank 0

extern const unsigned char schild2[];

#endif

/* End of SHIELD-2.H */
