/*

 SHIELD-1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __shield_1_h_INCLUDE
#define __shield_1_h_INCLUDE

#define schild1Width 18
#define schild1Height 4
#define schild1Bank 0

extern const unsigned char shield1[];

#endif

/* End of SHIELD-1.H */
