/*

 GAMEOVER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 20
   Tile set      : Z:\home\magister\repos\github\vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __gameover_h_INCLUDE
#define __gameover_h_INCLUDE

#define gameoverWidth 20
#define gameoverHeight 20
#define gameoverBank 0

extern const unsigned char gameover[];

#endif

/* End of GAMEOVER.H */
