/*

 TITLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 20
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __title_h_INCLUDE
#define __title_h_INCLUDE

#define titleWidth 20
#define titleHeight 20
#define titleBank 0

extern const unsigned char title[];

#endif

/* End of TITLE.H */
