/*

 GAMEBORDER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __gameborder_h_INCLUDE
#define __gameborder_h_INCLUDE

#define gameborderWidth 20
#define gameborderHeight 18
#define gameborderBank 0

extern const unsigned char gameborder[];

#endif

/* End of GAMEBORDER.H */
