/*

 TEXTBORDER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : Z:\home\magister\repos\codeberg\klauen\gfx\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __textborder_h_INCLUDE
#define __textborder_h_INCLUDE

#define rahmenWidth 20
#define rahmenHeight 6
#define rahmenBank 0

extern const unsigned char textborder[];

#endif

/* End of TEXTBORDER.H */
