/*

 ROOM12.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room12_h_INCLUDE
#define __room12_h_INCLUDE

#define room12Width 18
#define room12Height 14
#define room12Bank 0

extern const unsigned char room12[];

#endif

/* End of ROOM12.H */
