/*

 ROOM1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room1_h_INCLUDE
#define __room1_h_INCLUDE

#define room1Width 18
#define room1Height 14
#define room1Bank 0



#endif

/* End of ROOM1.H */
