/*

 ROOM10.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room10_h_INCLUDE
#define __room10_h_INCLUDE

#define room10Width 18
#define room10Height 14
#define room10Bank 0

extern const unsigned char room10[];

#endif

/* End of ROOM10.H */
