/*

 ROOM9.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\codeberg\Vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room9_h_INCLUDE
#define __room9_h_INCLUDE

#define room9Width 18
#define room9Height 14
#define room9Bank 0

extern const unsigned char room9[];

#endif

/* End of ROOM9.H */
