/*

 ROOM15.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\github\vampkiller\gfx\tilesets\font-and-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room15_h_INCLUDE
#define __room15_h_INCLUDE

#define room15Width 18
#define room15Height 14
#define room15Bank 0

extern const unsigned char room15[];

#endif

/* End of ROOM15.H */
